# Generated by Django 5.2.13 on 2026-06-08 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=190)),
                ('slug', models.SlugField(max_length=190)),
                ('description', models.TextField()),
                ('width', models.PositiveIntegerField(default=2000)),
                ('height', models.PositiveIntegerField(default=1200)),
                ('grid_size', models.PositiveIntegerField(default=10)),
                ('snap_enabled', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pretix_plan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pretixbase.seatingplan')),
                ('scope_organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smartseat_plans', to='pretixbase.organizer')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('scope_organizer', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SeatingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('is_accessible_zone', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='pretix_smartseating.seatingplan')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('plan', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('price_rank', models.PositiveIntegerField(default=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_categories', to='pretix_smartseating.seatingplan')),
            ],
            options={
                'ordering': ['price_rank', 'name'],
                'unique_together': {('plan', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SeatingPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('layout_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pretix_smartseating.seatingplan')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('plan', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30)),
                ('row_index', models.IntegerField(default=0)),
                ('y', models.FloatField(default=0)),
                ('curvature', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pretix_smartseating.seatingarea')),
            ],
            options={
                'ordering': ['row_index', 'label'],
                'unique_together': {('area', 'label')},
            },
        ),
        migrations.CreateModel(
            name='SeatingTemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=190)),
                ('source_kind', models.CharField(default='image', max_length=20)),
                ('source_mime', models.CharField(max_length=120)),
                ('source_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='smartseating/templates/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('opacity', models.FloatField(default=0.35)),
                ('z_index', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assets', to='pretix_smartseating.seatingplan')),
            ],
            options={
                'ordering': ['z_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventSeatPlanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('allow_nearby_mode', models.BooleanField(default=True)),
                ('prefer_center', models.BooleanField(default=True)),
                ('prefer_front', models.BooleanField(default=False)),
                ('hold_timeout_seconds', models.PositiveIntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartseat_mappings', to='pretixbase.event')),
                ('subevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smartseat_mappings', to='pretixbase.subevent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_mappings', to='pretix_smartseating.seatingplan')),
                ('active_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pretix_smartseating.seatingplanversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'subevent'), name='smartseat_unique_mapping_per_event_subevent')],
            },
        ),
        migrations.CreateModel(
            name='SeatDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('external_id', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=190)),
                ('block_label', models.CharField(max_length=30)),
                ('row_label', models.CharField(max_length=30)),
                ('seat_number', models.CharField(max_length=30)),
                ('seat_index', models.IntegerField(default=0)),
                ('row_index', models.IntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('seat_type', models.CharField(default='normal', max_length=20)),
                ('is_accessible', models.BooleanField(default=False)),
                ('is_companion', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_technical_blocked', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretix_smartseating.seatcategory')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='pretix_smartseating.seatingarea')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='pretix_smartseating.seatingplan')),
                ('row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='pretix_smartseating.seatingrow')),
            ],
            options={
                'ordering': ['block_label', 'row_index', 'seat_index'],
                'indexes': [models.Index(fields=['plan', 'block_label', 'row_label', 'seat_index'], name='pretix_smar_plan_id_0b1abe_idx'), models.Index(fields=['plan', 'external_id'], name='pretix_smar_plan_id_cb661b_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'external_id'), name='smartseat_unique_external_id'), models.UniqueConstraint(fields=('plan', 'block_label', 'row_label', 'seat_number'), name='smartseat_unique_visible_position')],
            },
        ),
    ]
