# Generated by Django 5.2.13 on 2026-06-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_smartseating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplan',
            name='area_shapes',
            field=models.JSONField(default=list),
        ),
    ]
