# Generated by Django 5.2.13 on 2026-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_smartseating', '0002_seatingplan_area_shapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplan',
            name='seat_groups',
            field=models.JSONField(default=list),
        ),
    ]
