# Generated by Django 5.2.13 on 2026-06-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_smartseating', '0003_seatingplan_seat_groups'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seatdefinition',
            name='smartseat_unique_visible_position',
        ),
    ]
