# Generated by Django 5.2.13 on 2026-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_smartseating', '0004_remove_seatdefinition_smartseat_unique_visible_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplan',
            name='zones',
            field=models.JSONField(default=list),
        ),
    ]
