# Generated by Django 5.2.13 on 2026-06-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_smartseating', '0005_seatingplan_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseatplanmapping',
            name='active_version',
        ),
        migrations.RemoveField(
            model_name='eventseatplanmapping',
            name='allow_nearby_mode',
        ),
        migrations.RemoveField(
            model_name='eventseatplanmapping',
            name='hold_timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='eventseatplanmapping',
            name='prefer_center',
        ),
        migrations.RemoveField(
            model_name='eventseatplanmapping',
            name='prefer_front',
        ),
    ]
